services:
  - type: web
    name: content-transformer-backend
    env: python
    region: singapore # or oregon / frankfurt
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: APP_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
