import os
import re
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from typing import Dict, Any, List
from app.config import settings

class DocxExportGenerator:
    """Generates professional styled Word (.docx) multi-page documents from generated artefacts."""

    @staticmethod
    def render_docx(title: str, content: str, output_filename: str, metadata: Dict[str, Any] = None) -> str:
        doc = Document()

        # Set default font
        style = doc.styles['Normal']
        font = style.font
        font.name = 'Calibri'
        font.size = Pt(11)
        font.color.rgb = RGBColor(30, 41, 59)

        # Header Title
        title_p = doc.add_paragraph()
        title_run = title_p.add_run(title)
        title_run.font.size = Pt(22)
        title_run.font.bold = True
        title_run.font.color.rgb = RGBColor(15, 23, 42)
        title_p.space_after = Pt(4)

        # Subtitle / Metadata badge
        meta_p = doc.add_paragraph()
        meta_run = meta_p.add_run("Generated by AI Content Transformer • Verified Multi-Artefact Platform")
        meta_run.font.size = Pt(9.5)
        meta_run.font.italic = True
        meta_run.font.color.rgb = RGBColor(100, 116, 139)
        meta_p.space_after = Pt(16)

        # Process Markdown lines
        lines = content.split("\n")
        in_table = False
        table_rows: List[List[str]] = []

        def flush_table():
            nonlocal in_table, table_rows
            if not table_rows:
                in_table = False
                return

            cols_count = max(len(r) for r in table_rows)
            table = doc.add_table(rows=len(table_rows), cols=cols_count)
            table.alignment = WD_TABLE_ALIGNMENT.CENTER
            table.style = 'Light Shading Accent 1' if 'Light Shading Accent 1' in doc.styles else 'Table Grid'

            for r_idx, row in enumerate(table_rows):
                for c_idx, cell_value in enumerate(row):
                    if c_idx < cols_count:
                        cell = table.cell(r_idx, c_idx)
                        cell.text = cell_value.strip("*`_ ")
                        if r_idx == 0:
                            # Header bolding
                            for p in cell.paragraphs:
                                for r in p.runs:
                                    r.font.bold = True

            doc.add_paragraph().paragraph_format.space_after = Pt(6)
            table_rows = []
            in_table = False

        for line in lines:
            line_str = line.strip()
            if not line_str:
                if in_table:
                    flush_table()
                continue

            # Table row detection
            if line_str.startswith("|") and line_str.endswith("|"):
                # Skip separator lines like |---|---|
                if re.match(r"^\|(\s*:?-+:?\s*\|)+$", line_str):
                    continue
                cells = [c.strip() for c in line_str.strip("|").split("|")]
                table_rows.append(cells)
                in_table = True
                continue
            elif in_table:
                flush_table()

            # Multi-page Page Break Detection
            if "PAGE 2" in line_str.upper() or "PAGE 3" in line_str.upper() or "PAGE BREAK" in line_str.upper():
                doc.add_page_break()

            if line_str.startswith("# "):
                h = doc.add_heading(level=1)
                hrun = h.add_run(line_str[2:].replace("**", "").replace("`", ""))
                hrun.font.size = Pt(16)
                hrun.font.bold = True
                hrun.font.color.rgb = RGBColor(15, 23, 42)
                h.paragraph_format.space_before = Pt(14)
                h.paragraph_format.space_after = Pt(6)
            elif line_str.startswith("## "):
                h = doc.add_heading(level=2)
                hrun = h.add_run(line_str[3:].replace("**", "").replace("`", ""))
                hrun.font.size = Pt(13)
                hrun.font.bold = True
                hrun.font.color.rgb = RGBColor(30, 41, 59)
                h.paragraph_format.space_before = Pt(12)
                h.paragraph_format.space_after = Pt(4)
            elif line_str.startswith("### "):
                h = doc.add_heading(level=3)
                hrun = h.add_run(line_str[4:].replace("**", "").replace("`", ""))
                hrun.font.size = Pt(11.5)
                hrun.font.bold = True
                hrun.font.color.rgb = RGBColor(51, 65, 85)
                h.paragraph_format.space_before = Pt(8)
                h.paragraph_format.space_after = Pt(2)
            elif line_str.startswith("- ") or line_str.startswith("* "):
                p = doc.add_paragraph(style='List Bullet')
                p.add_run(line_str[2:].replace("**", "").replace("`", ""))
                p.paragraph_format.space_after = Pt(3)
            elif re.match(r"^\d+\.\s", line_str):
                p = doc.add_paragraph(style='List Number')
                clean_text = re.sub(r"^\d+\.\s*", "", line_str).replace("**", "").replace("`", "")
                p.add_run(clean_text)
                p.paragraph_format.space_after = Pt(3)
            elif line_str.startswith("> "):
                p = doc.add_paragraph()
                run = p.add_run(line_str[2:].replace("**", "").replace("`", ""))
                run.font.italic = True
                run.font.color.rgb = RGBColor(71, 85, 105)
                p.paragraph_format.left_indent = Inches(0.4)
                p.paragraph_format.space_after = Pt(6)
            elif line_str.startswith("---"):
                continue
            else:
                p = doc.add_paragraph()
                p.add_run(line_str.replace("**", "").replace("`", ""))
                p.paragraph_format.space_after = Pt(6)

        if in_table:
            flush_table()

        out_path = os.path.join(settings.EXPORT_DIR, output_filename)
        doc.save(out_path)
        return out_path
